# importing required libraries

In [1]:
import pandas as pd
import numpy as np

# importing data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism-preprocessed.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

# creating targets

In [3]:
data_preprocessed['Absenteeism Time in Hours'].median()

# we will consider every member ubsent more than 3 hrs as exencively absent
# if less than 3 then not

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] >
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1,0)
# if element is < 3 then 0
# else > 3 then 1

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

# basically mapping the column elements where all n<3 are 0 and all n>=3 are 1

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

# comment of targets
## due to use of medial roughly 50% of dataset will be 1 and remaining will me 0

In [7]:
targets.sum() / targets.shape[0]
# roughly 46% of data is 1

0.45571428571428574

# creating a checkpoint

In [8]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis = 1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive Absenteeism  
0               30          0         2    1                      1  
1               31          0         1    0                      0  
2               31          0         0    0                      0  
3               24          0         2    0                      1  
4               30          0         2    1                      0

In [9]:
data_with_targets is data_preprocessed

#  checking if two dataframes are equal

False

### selecting inputs for logistic regression

In [10]:
data_with_targets.iloc[:,0:14]
# n:m,N:m => row:col indices

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  
0                 30          0         2    1  
1                 31          0         1    0  
2                 31          0         0    0  
3                 24          0         2    0  
4                 30          0         2    1  
..               ...        ...       ...  ...  
695               22          1         2    0  
696               24          0         1    2  
697               25          1         0    0  
698               25          1         0    0  
699               25          0         1    1  

[700 rows x 14 columns]

In [11]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

# dose same thing as iloc above but omits last column

# standardizing the data

In [12]:
# standardize the inputs

# standardization is one of the most common preprocessing tools
# since data of different magnitude (scale) can be biased towards high values,
# we want all inputs to be of similar magnitude
# this is a peculiarity of machine learning in general - most (but not all) algorithms do badly with unscaled data

# a very useful module we can use is StandardScaler 
# it has much more capabilities than the straightforward 'preprocessing' method
from sklearn.preprocessing import StandardScaler


# we will create a variable that will contain the scaling information for this particular dataset
# here's the full documentation: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

# define scaler as an object
absenteeism_scaler = StandardScaler()

In [13]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [14]:
# check what are all columns that we've got
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [15]:
# choose the columns to scale
# we later augmented this code and put it in comments
# columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']
    
# select the columns to omit
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [16]:
# create the columns to scale, based on the columns to omit
# use list comprehension to iterate over the list
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

columns_to_scale

['Month Value',
 'Day of the Week',
 'Transportation Expense',
 'Distance to Work',
 'Age',
 'Daily Work Load Average',
 'Body Mass Index',
 'Children',
 'Pet']

In [17]:
# declare a scaler object, specifying the columns you want to scale
absenteeism_scaler = CustomScaler(columns_to_scale)

In [18]:
# fit the data (calculate mean and standard deviation); they are automatically stored inside the object 
scaled_inputs = absenteeism_scaler.fit_transform(unscaled_inputs)


C:\Users\DELL\anaconda3\envs\py3-TF2.0\lib\site-packages\numpy\core\fromnumeric.py:3502: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


In [19]:
# # standardizes the data, using the transform method 
# # in the last line, we fitted the data - in other words
# # we found the internal parameters of a model that will be used to transform data. 
# # transforming applies these parameters to our data
# # note that when you get new data, you can just call 'scaler' again and transform it in the same way as now
# scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [20]:
# the scaled_inputs are now an ndarray, because sklearn works with ndarrays
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1     0.030796        -0.800950   
1           0         0         0         0     0.030796        -0.800950   
2           0         0         0         1     0.030796        -0.232900   
3           1         0         0         0     0.030796         0.335149   
4           0         0         0         1     0.030796         0.335149   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0    -0.568019        -0.232900   
696         1         0         0         0    -0.568019        -0.232900   
697         1         0         0         0    -0.568019         0.335149   
698         0         0         0         1    -0.568019         0.335149   
699         0         0         0         1    -0.568019         0.335149   

     Transportation Expense  Distance to Work       Age  \
0                  1.005844          0.412816 -0.536062   
1                 -1.574681         -1.141882  2.130803   
2                 -0.654143          1.426749  0.248310   
3                  0.854936         -1.682647  0.405184   
4                  1.005844          0.412816 -0.536062   
..                      ...               ...       ...   
695               -0.654143         -0.533522  0.562059   
696                0.040034         -0.263140 -1.320435   
697                1.624567         -0.939096 -1.320435   
698                0.190942         -0.939096 -0.692937   
699                1.036026          0.074838  0.562059   

     Daily Work Load Average  Body Mass Index  Education  Children       Pet  
0                  -0.806331         0.767431          0  0.880469  0.268487  
1                  -0.806331         1.002633          0 -0.019280 -0.589690  
2                  -0.806331         1.002633          0 -0.919030 -0.589690  
3                  -0.806331        -0.643782          0  0.880469 -0.589690  
4                  -0.806331         0.767431          0  0.880469  0.268487  
..                       ...              ...        ...       ...       ...  
695                -0.853789        -1.114186          1  0.880469 -0.589690  
696                -0.853789        -0.643782          0 -0.019280  1.126663  
697                -0.853789        -0.408580          1 -0.919030 -0.589690  
698                -0.853789        -0.408580          1 -0.919030 -0.589690  
699                -0.853789        -0.408580          0 -0.019280  0.268487  

[700 rows x 14 columns]

# cells below are used where dummy vars were standardised as well

In [21]:
# from sklearn.preprocessing import StandardScaler

In [22]:
# absenteeism_scaler = StandardScaler()
# # new empty object of StandardScaler

In [23]:
# absenteeism_scaler.fit(unscaled_inputs)

# # calculates mean and std.deviation for all features in dataframe

In [24]:
# scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

# # transforms the features or standardises them 
# # subracting by mean and deviding by std. deviation (for all elements in the series)

In [25]:
# print(scaled_inputs)
# scaled_inputs.shape

# Spliting the data in train and test data    also shuffling it

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
train_test_split(scaled_inputs, targets)
# giving the method features and targets or inputs and outputs

# we get 4 arrays train input ,train output     and     test input , test output

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
 191         1         0         0         0    -0.268611         1.471248   
 562         0         0         1         0     1.527833         0.903199   
 299         1         0         0         0     0.929019         0.903199   
 611         1         0         0         0    -1.466241        -1.368999   
 463         1         0         0         0     0.929019         1.471248   
 ..        ...       ...       ...       ...          ...              ...   
 207         0         0         1         0    -1.166834         1.471248   
 66          0         0         0         1     0.929019         0.903199   
 373         0         0         0         1     0.929019        -1.368999   
 421         0         0         0         1    -0.867426         0.903199   
 304         0         0         0         1     0.929019        -0.232900   
 
      Transportation Expense  Distance to Work       Age  \
 1

In [28]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20 )
# storing the four arrays in arbitrary standard variables 
#  0.8 is 80-20 split
#  random_state is shuffling data randmolly but only one way everytime

In [29]:
print(x_train.shape ,y_train.shape)

# x means features 
# y means targets 

# training features and targets

(560, 14) (560,)


In [30]:
print(x_test.shape ,y_test.shape)


# x means features 
# y means targets 

# testing features and targets

(140, 14) (140,)


# finally creating the model

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# importing required libraries

In [32]:
reg = LogisticRegression()

# object of LogisticRegression

In [33]:
reg.fit(x_train,y_train)

# creation of model x is input while y is required result for each input array

LogisticRegression()

In [34]:
reg.score(x_train,y_train)

# measures accuracy of the model
# 78% approx

0.7660714285714286

### manually measuring accuracy

In [35]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [36]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [37]:
model_outputs == y_train


#  compare model_outputs with targets array in training set

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [38]:
np.sum((model_outputs == y_train))

# this will give total number of right predictions

429

In [39]:
model_outputs.shape[0]
# total number of elements in array

560

In [40]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

# calculate accuracy that is  right_predictions / total_no_of_predictions


0.7660714285714286

# finding  the intercept and coefficient

In [41]:
reg.intercept_

array([-1.60991897])

In [42]:
reg.coef_

array([[ 2.78809595,  0.92273475,  3.10358519,  0.81724476,  0.01379249,
        -0.07594179,  0.62737945, -0.02990801, -0.17344994, -0.02273184,
         0.2816181 , -0.27058935,  0.36063506, -0.27446609]])

In [43]:
unscaled_inputs.columns.values


array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [44]:
feature_name = unscaled_inputs.columns.values


## creating summary table

In [45]:
summary_table = pd.DataFrame (columns = ['Feature name'], data = feature_name)

In [46]:
summary_table['Coefficient'] = np.transpose(reg.coef_)

In [47]:
summary_table

Feature name  Coefficient
0                  Reason_1     2.788096
1                  Reason_2     0.922735
2                  Reason_3     3.103585
3                  Reason_4     0.817245
4               Month Value     0.013792
5           Day of the Week    -0.075942
6    Transportation Expense     0.627379
7          Distance to Work    -0.029908
8                       Age    -0.173450
9   Daily Work Load Average    -0.022732
10          Body Mass Index     0.281618
11                Education    -0.270589
12                 Children     0.360635
13                      Pet    -0.274466

In [48]:
summary_table.index = summary_table.index + 1
# shifting index one space ahead

In [49]:
summary_table.loc[0] = ['intercept' , reg.intercept_[0]]

# inseting value of intercept at new index
summary_table

Feature name  Coefficient
1                  Reason_1     2.788096
2                  Reason_2     0.922735
3                  Reason_3     3.103585
4                  Reason_4     0.817245
5               Month Value     0.013792
6           Day of the Week    -0.075942
7    Transportation Expense     0.627379
8          Distance to Work    -0.029908
9                       Age    -0.173450
10  Daily Work Load Average    -0.022732
11          Body Mass Index     0.281618
12                Education    -0.270589
13                 Children     0.360635
14                      Pet    -0.274466
0                 intercept    -1.609919

In [50]:
summary_table = summary_table.sort_index()

# sorting indices
summary_table

Feature name  Coefficient
0                 intercept    -1.609919
1                  Reason_1     2.788096
2                  Reason_2     0.922735
3                  Reason_3     3.103585
4                  Reason_4     0.817245
5               Month Value     0.013792
6           Day of the Week    -0.075942
7    Transportation Expense     0.627379
8          Distance to Work    -0.029908
9                       Age    -0.173450
10  Daily Work Load Average    -0.022732
11          Body Mass Index     0.281618
12                Education    -0.270589
13                 Children     0.360635
14                      Pet    -0.274466

 # summary_table odds ratio

In [51]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

# using the exponential function to get the real values from    log values as logistic regression is log(odds) equation
summary_table

Feature name  Coefficient  Odds_ratio
0                 intercept    -1.609919    0.199904
1                  Reason_1     2.788096   16.250049
2                  Reason_2     0.922735    2.516162
3                  Reason_3     3.103585   22.277678
4                  Reason_4     0.817245    2.264253
5               Month Value     0.013792    1.013888
6           Day of the Week    -0.075942    0.926870
7    Transportation Expense     0.627379    1.872697
8          Distance to Work    -0.029908    0.970535
9                       Age    -0.173450    0.840759
10  Daily Work Load Average    -0.022732    0.977525
11          Body Mass Index     0.281618    1.325273
12                Education    -0.270589    0.762930
13                 Children     0.360635    1.434240
14                      Pet    -0.274466    0.759978

In [53]:
# what we infer is 

# odds_ratio near to 1 is sign of redundant feature
#  or you can say this feature is less usefull when other features come into the picture 
#  or these features dont matter thatmuch when other features are used for regression

  # finally testing the model using  the test data set

In [54]:
reg.score(x_test,y_test)

0.7571428571428571

In [58]:
predicted_probablitiy = reg.predict_proba(x_test)
predicted_probablitiy

# inbuit method in python for predicted probability 

#probability of 0 and probability on 1

array([[0.75835265, 0.24164735],
       [0.62498802, 0.37501198],
       [0.45440874, 0.54559126],
       [0.77426   , 0.22574   ],
       [0.07523779, 0.92476221],
       [0.28681936, 0.71318064],
       [0.30073948, 0.69926052],
       [0.11193452, 0.88806548],
       [0.75347284, 0.24652716],
       [0.75760515, 0.24239485],
       [0.49756376, 0.50243624],
       [0.18139028, 0.81860972],
       [0.06978241, 0.93021759],
       [0.67883884, 0.32116116],
       [0.27957168, 0.72042832],
       [0.49797848, 0.50202152],
       [0.51589736, 0.48410264],
       [0.55051804, 0.44948196],
       [0.38313924, 0.61686076],
       [0.05676825, 0.94323175],
       [0.73363565, 0.26636435],
       [0.76663108, 0.23336892],
       [0.44371138, 0.55628862],
       [0.46099097, 0.53900903],
       [0.22525807, 0.77474193],
       [0.7535073 , 0.2464927 ],
       [0.49490369, 0.50509631],
       [0.87493323, 0.12506677],
       [0.23623712, 0.76376288],
       [0.75882465, 0.24117535],
       [0.

In [59]:
predicted_probablitiy.shape

(140, 2)

In [64]:
predicted_probablitiy[:,1]

# this is the probability of getting one 

array([0.24164735, 0.37501198, 0.54559126, 0.22574   , 0.92476221,
       0.71318064, 0.69926052, 0.88806548, 0.24652716, 0.24239485,
       0.50243624, 0.81860972, 0.93021759, 0.32116116, 0.72042832,
       0.50202152, 0.48410264, 0.44948196, 0.61686076, 0.94323175,
       0.26636435, 0.23336892, 0.55628862, 0.53900903, 0.77474193,
       0.2464927 , 0.50509631, 0.12506677, 0.76376288, 0.24117535,
       0.39918393, 0.72047675, 0.68231942, 0.50353998, 0.23336892,
       0.57784928, 0.26023495, 0.75743911, 0.45350431, 0.5903656 ,
       0.25199485, 0.45191141, 0.24236434, 0.39437621, 0.8030637 ,
       0.63740889, 0.73819425, 0.24982618, 0.26669706, 0.21539655,
       0.51862303, 0.3061877 , 0.68974674, 0.26077087, 0.84058793,
       0.4196596 , 0.91483074, 0.29400699, 0.31478632, 0.30997231,
       0.73234382, 0.66455837, 0.28795543, 0.78613859, 0.24913302,
       0.24371337, 0.07494652, 0.24870204, 0.76501224, 0.32537572,
       0.25137072, 0.31368394, 0.89488667, 0.44831462, 0.61226

# saving the model 

 using python modlue pickle 

In [65]:
import pickle

In [72]:
with open('model', 'wb') as file:

    pickle.dump(reg,file)
    
# model = name of the exported model
# wb = write bytes    used when pickling
# rb = read bytes     used when unpickling

# dump = method implies we want to save the model
# reg = is the object from our code we want to save

# load = method to import or use the model


In [73]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler,file)

### there are some dis.adv of pickle such as 
1. slow
2. does not support diff versions of pythod
3. security

to save is as a module now we have to use object oriented programming

In [74]:
import numpy as np
import pandas as pd
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin


class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.array(np.mean(X[self.columns]))
        self.var_ = np.array(np.var(X[self.columns]))
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]



class absenteeism_model():
      
        def __init__(self, model_file, scaler_file):
            # read the 'model' and 'scaler' files which were saved
            with open('model','rb') as model_file, open('scaler', 'rb') as scaler_file:
                self.reg = pickle.load(model_file)
                self.scaler = pickle.load(scaler_file)
                self.data = None
        
        # take a data file (*.csv) and preprocess it in the same way as in the lectures
        def load_and_clean_data(self, data_file):
            
            # import the data
            df = pd.read_csv(data_file,delimiter=',')
            # store the data in a new variable for later use
            self.df_with_predictions = df.copy()
            # drop the 'ID' column
            df = df.drop(['ID'], axis = 1)
            # to preserve the code we've created in the previous section, we will add a column with 'NaN' strings
            df['Absenteeism Time in Hours'] = 'NaN'

            # create a separate dataframe, containing dummy values for ALL avaiable reasons
            reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first = True)
            
            # split reason_columns into 4 types
            reason_type_1 = reason_columns.loc[:,1:14].max(axis=1)
            reason_type_2 = reason_columns.loc[:,15:17].max(axis=1)
            reason_type_3 = reason_columns.loc[:,18:21].max(axis=1)
            reason_type_4 = reason_columns.loc[:,22:].max(axis=1)
            
            # to avoid multicollinearity, drop the 'Reason for Absence' column from df
            df = df.drop(['Reason for Absence'], axis = 1)
            
            # concatenate df and the 4 types of reason for absence
            df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis = 1)
            
            # assign names to the 4 reason type columns
            # note: there is a more universal version of this code, however the following will best suit our current purposes             
            column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
                           'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
                           'Pet', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']
            df.columns = column_names

            # re-order the columns in df
            column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Date', 'Transportation Expense', 
                                      'Distance to Work', 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education', 
                                      'Children', 'Pet', 'Absenteeism Time in Hours']
            df = df[column_names_reordered]
      
            # convert the 'Date' column into datetime
            df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

            # create a list with month values retrieved from the 'Date' column
            list_months = []
            for i in range(df.shape[0]):
                list_months.append(df['Date'][i].month)

            # insert the values in a new column in df, called 'Month Value'
            df['Month Value'] = list_months

            # create a new feature called 'Day of the Week'
            df['Day of the Week'] = df['Date'].apply(lambda x: x.weekday())


            # drop the 'Date' column from df
            df = df.drop(['Date'], axis = 1)

            # re-order the columns in df
            column_names_upd = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value', 'Day of the Week',
                                'Transportation Expense', 'Distance to Work', 'Age',
                                'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
                                'Pet', 'Absenteeism Time in Hours']
            df = df[column_names_upd]


            # map 'Education' variables; the result is a dummy
            df['Education'] = df['Education'].map({1:0, 2:1, 3:1, 4:1})

            # replace the NaN values
            df = df.fillna(value=0)

            # drop the original absenteeism time
            df = df.drop(['Absenteeism Time in Hours'],axis=1)
            
            # drop the variables we decide we don't need
            df = df.drop(['Day of the Week','Daily Work Load Average','Distance to Work'],axis=1)
            
            # we have included this line of code if you want to call the 'preprocessed data'
            self.preprocessed_data = df.copy()
            
            # we need this line so we can use it in the next functions
            self.data = self.scaler.transform(df)
    
        # a function which outputs the probability of a data point to be 1
        def predicted_probability(self):
            if (self.data is not None):  
                pred = self.reg.predict_proba(self.data)[:,1]
                return pred
        
        # a function which outputs 0 or 1 based on our model
        def predicted_output_category(self):
            if (self.data is not None):
                pred_outputs = self.reg.predict(self.data)
                return pred_outputs
        
        # predict the outputs and the probabilities and 
        # add columns with these values at the end of the new data
        def predicted_outputs(self):
            if (self.data is not None):
                self.preprocessed_data['Probability'] = self.reg.predict_proba(self.data)[:,1]
                self.preprocessed_data ['Prediction'] = self.reg.predict(self.data)
                return self.preprocessed_data

